#!/usr/bin/env python3
"""Embed a TTF into a C++ header as a byte array.

ImGui loads fonts from memory, so bundling the face as a byte array keeps the
build self-contained: no runtime fetch, no extra request, and it works the same
in the WASM build and the headless smoke test.

Usage:
    python tools/ttf_to_header.py assets/fonts/SpaceGrotesk-Subset.ttf \
        app/third_party/space_grotesk_data.h
"""
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    source, destination = sys.argv[1], sys.argv[2]
    with open(source, "rb") as handle:
        data = handle.read()

    if not data:
        print(f"error: {source} is empty")
        return 1

    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + " ".join(f"0x{byte:02x}," for byte in chunk))

    with open(destination, "w", encoding="ascii", newline="\n") as handle:
        handle.write("// Generated by tools/ttf_to_header.py - do not edit by hand.\n")
        handle.write("// Source: Space Grotesk, SIL Open Font License 1.1 (see assets/fonts/OFL.txt).\n")
        handle.write("// Latin subset, static Regular (wght 400).\n")
        handle.write("#pragma once\n\n")
        handle.write(f"static const unsigned int kSpaceGroteskSize = {len(data)}u;\n\n")
        handle.write("static const unsigned char kSpaceGrotesk[] = {\n")
        handle.write("\n".join(lines))
        handle.write("\n};\n")

    print(f"wrote {destination} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
